### ISSUE TITLE
Outdated gulp-ng-annotate version

### ISSUE THREAD

**Issue by georgebejan** [Catalysts/cat-angular#45]
I get the following error when I try to run 'gulpw' on cloned cat-angular:

`TypeError: Cannot assign to read only property '$methodName' of false
    at matchRegular (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\build\es5\ng-annotate-main.js:272:24)
    at match (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\build\es5\ng-annotate-main.js:32:10)
    at traverse.post (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\build\es5\ng-annotate-main.js:912:23)
    at visit (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:50:13)
    at visit (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:44:21)
    at visit (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:44:21)
    at visit (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:41:25)
    at visit (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:44:21)
    at visit (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:41:25)
    at visit (C:\catalysts\Apps\cat-angular\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:44:21)
`

After some googling I found out that this can be solved by updating the version of  `gulp-ng-annotate`.

>Well, the update commant does not work as expected. But I found a way which really updates the package and solves the issue
1. manually change the version in package.json to "grunt-ng-annotate": "^1.0.1"
2. run npm install
3. Issue is solved.

Solution was found [here](https://github.com/olov/ng-annotate/issues/139)

**Comment by tscheinecker** [comment]
ng-annotate works fine for me, but i'm currently in the process of updating all npm dependencies anyway (which should hopefully be finished today), so please stay tuned :)

**Comment by tscheinecker** [comment]
just updated the npm dependencies and the release worked without any problems, so everything should work fine
